[package]
name = "mkheaders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
mktemp = "0.5.0"
rayon = "1.6.1"
regex = "1.7.1"
strsim = "0.10.0"
